apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: # soft limit
        memory: "68mi"
        cpu: "100m"
      limits: # Hard limit
        memory: "68mi"
        cpu: "100m"

