apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value : "devops"
    - name : trainer
      vlaue : "shiva"