apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: pod-configmap