apiVersion: v1
kind: Pod
metadata:
  name: env-secret
  labels:
    purpose: demonstrate-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:
          name: pod-secret