apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # Deployment set labels
  labels:
    purpose: Deployment-demo
    project: roboshop
    app: nginx
spec:
  replicas: 2
   # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: Deployment-demo
      project: roboshop
      app: nginx
      environment: dev

  # This is pod definition
  template:
    metadata:
      labels:
        purpose: Deployment-demo
        project: roboshop
        app: nginx
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx

#Service created according to session 62

# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   labels:
#     purpose: service-demo
# spec:
#   selector:
#     purpose: Deployment-demo
#     project: roboshop
#     app: nginx
#     environment: dev
#   ports:
#     - protocol: TCP
#       port: 80 # service port
#       targetPort: 80 # container port